# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCollectcardinfo():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_collectcardinfo(self):
    self.driver.get("https://app.privacy.com/home")
    self.driver.set_window_size(1187, 1133)
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"card-pan\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"card-cvv\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"card-exp\"]").click()
  
