# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCrunchyrollmonthyearselection():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_crunchyrollmonthyearselection(self):
    dropdown = self.driver.find_element(By.ID, "billing_exp_month")
    dropdown.find_element(By.XPATH, "//option[. = '05 - May']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#billing_exp_month > option:nth-child(6)").click()
    dropdown = self.driver.find_element(By.ID, "billing_exp_year")
    dropdown.find_element(By.XPATH, "//option[. = '2030']").click()
    self.driver.find_element(By.CSS_SELECTOR, "#billing_exp_year > option:nth-child(8)").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
