# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestCreateburnercard():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_createburnercard(self):
    self.driver.get("https://app.privacy.com/home/")
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"new-card\"]").click()
    self.driver.find_element(By.CSS_SELECTOR, ".-nickname > .value").click()
    self.driver.find_element(By.ID, "modal-card-edit-nickname-input").send_keys("ide_test_1")
    self.driver.find_element(By.CSS_SELECTOR, ".pill-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".description").click()
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"spend-limit-input\"]").send_keys("$3")
    self.driver.find_element(By.CSS_SELECTOR, ".duration-button:nth-child(5)").click()
    self.driver.find_element(By.CSS_SELECTOR, ".pill-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".create-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".modal-close > .bi-x").click()
  
